// Mumbai Suburban Railway — operational stations across Western, Central
// (incl. NE Kasara + SE Khopoli branches), Harbour, Trans-Harbour, Uran, and
// the Vasai–Diva / Panvel link stations. Deduplicated and alphabetized.

export const STATIONS: string[] = [
  'Airoli',
  'Ambarnath',
  'Ambivli',
  'Andheri',
  'Asangaon',
  'Atgaon',
  'Badlapur',
  'Bamandongri',
  'Bandra',
  'Bhandup',
  'Bhayandar',
  'Bhivpuri Road',
  'Boisar',
  'Borivali',
  'Byculla',
  'CBD Belapur',
  'CSMT (Chhatrapati Shivaji Maharaj Terminus)',
  'Charni Road',
  'Chembur',
  'Chinchpokli',
  'Chunabhatti',
  'Churchgate',
  'Cotton Green',
  'Currey Road',
  'Dadar',
  'Dahanu Road',
  'Dahisar',
  'Dativali',
  'Digha Gaon',
  'Diva Junction',
  'Dockyard Road',
  'Dolavli',
  'Dombivli',
  'Dronagiri',
  'GTB Nagar',
  'Gavhan',
  'Ghansoli',
  'Ghatkopar',
  'Goregaon',
  'Govandi',
  'Grant Road',
  'Jogeshwari',
  'Juchandra',
  'Juinagar',
  'Kalamboli',
  'Kalwa',
  'Kalyan Junction',
  'Kaman Road',
  'Kandivli',
  'Kanjurmarg',
  'Karjat',
  'Kasara',
  'Kelavli',
  'Kelve Road',
  'Khadavli',
  'Khandeshwar',
  'Khar Road',
  'Kharbav',
  'Khardi',
  'Kharghar',
  'Kharkopar',
  'Khopoli',
  'Kings Circle',
  'Kopar',
  'Kopar Khairane',
  'Kurla',
  'Lower Parel',
  'Lowjee',
  'Mahalaxmi',
  'Mahim Junction',
  'Malad',
  'Mankhurd',
  'Mansarovar',
  'Marine Lines',
  'Masjid',
  'Matunga',
  'Matunga Road',
  'Mira Road',
  'Mulund',
  'Mumbai Central',
  'Mumbra',
  'Nahur',
  'Naigaon',
  'Nallasopara',
  'Navade Road',
  'Neral',
  'Nerul',
  'Nhava Sheva',
  'Nilaje',
  'Oombermali',
  'Palasdari',
  'Palghar',
  'Panvel',
  'Parel',
  'Prabhadevi',
  'Rabale',
  'Ram Mandir',
  'Ranjanpada',
  'Reay Road',
  'Sandhurst Road',
  'Sanpada',
  'Santacruz',
  'Saphale',
  'Seawoods–Darave',
  'Sewri',
  'Shahad',
  'Shelu',
  'Sion',
  'Taloja Panchanand',
  'Thakurli',
  'Thane',
  'Thansit',
  'Tilak Nagar',
  'Titwala',
  'Turbhe',
  'Ulhasnagar',
  'Umroli',
  'Uran',
  'Vaitarna',
  'Vangaon',
  'Vangani',
  'Vasai Road',
  'Vashi',
  'Vasind',
  'Vidyavihar',
  'Vikhroli',
  'Vile Parle',
  'Virar',
  'Vithalwadi',
  'Wadala Road',
];
